<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $provinces = [
            ['name' => 'Sindh'],
            ['name' => 'Punjab'],
            ['name' => 'Balochistan'],
            ['name' => 'Khyber Pakhtunkhwa'],
            ['name' => 'Gilgit Baltistan'],
            ['name' => 'Azad Jammu and Kashmir'],
        ];

        DB::table('provinces')->insert($provinces);


        $districts = [
            ['name' => 'Badin', 'province_id' => 1],
            ['name' => 'Dadu', 'province_id' => 1],
            ['name' => 'Ghotki', 'province_id' => 1],
            ['name' => 'Hyderabad', 'province_id' => 1],
            ['name' => 'Jacobabad', 'province_id' => 1],
            ['name' => 'Jamshoro', 'province_id' => 1],
            ['name' => 'Karachi', 'province_id' => 1],
            ['name' => 'Kashmore', 'province_id' => 1],
            ['name' => 'Khairpur', 'province_id' => 1],
            ['name' => 'Larkana', 'province_id' => 1],
            ['name' => 'Matiari', 'province_id' => 1],
            ['name' => 'Mirpur Khas', 'province_id' => 1],
            ['name' => 'Naushahro Feroze', 'province_id' => 1],
            ['name' => 'Sanghar', 'province_id' => 1],
            ['name' => 'Kambar Shahdadkot', 'province_id' => 1],
            ['name' => 'Shaheed Benazirabad', 'province_id' => 1],
            ['name' => 'Shikarpur', 'province_id' => 1],
            ['name' => 'Sujawal', 'province_id' => 1],
            ['name' => 'Sukkur', 'province_id' => 1],
            ['name' => 'Tando Allahyar', 'province_id' => 1],
            ['name' => 'Tando Muhammad Khan', 'province_id' => 1],
            ['name' => 'Tharparkar', 'province_id' => 1],
            ['name' => 'Thatta', 'province_id' => 1],
            ['name' => 'Umerkot', 'province_id' => 1],
            ['name' => 'Attock', 'province_id' => 2],
            ['name' => 'Bahawalnagar', 'province_id' => 2],
            ['name' => 'Bahawalpur', 'province_id' => 2],
            ['name' => 'Bhakkar', 'province_id' => 2],
            ['name' => 'Chakwal', 'province_id' => 2],
            ['name' => 'Chiniot', 'province_id' => 2],
            ['name' => 'Dera Ghazi Khan', 'province_id' => 2],
            ['name' => 'Faisalabad', 'province_id' => 2],
            ['name' => 'Gujranwala', 'province_id' => 2],
            ['name' => 'Gujrat', 'province_id' => 2],
            ['name' => 'Hafizabad', 'province_id' => 2],
            ['name' => 'Jhelum', 'province_id' => 2],
            ['name' => 'Jhang', 'province_id' => 2],
            ['name' => 'Kasur', 'province_id' => 2],
            ['name' => 'Khanewal', 'province_id' => 2],
            ['name' => 'Khushab', 'province_id' => 2],
            ['name' => 'Lahore', 'province_id' => 2],
            ['name' => 'Layyah', 'province_id' => 2],
            ['name' => 'Lodhran', 'province_id' => 2],
            ['name' => 'Mandi Bahauddin', 'province_id' => 2],
            ['name' => 'Mianwali', 'province_id' => 2],
            ['name' => 'Multan', 'province_id' => 2],
            ['name' => 'Muzaffargarh', 'province_id' => 2],
            ['name' => 'Nankana Sahib', 'province_id' => 2],
            ['name' => 'Narowal', 'province_id' => 2],
            ['name' => 'Okara', 'province_id' => 2],
            ['name' => 'Pakpattan', 'province_id' => 2],
            ['name' => 'Rahim Yar Khan', 'province_id' => 2],
            ['name' => 'Rajanpur', 'province_id' => 2],
            ['name' => 'Rawalpindi', 'province_id' => 2],
            ['name' => 'Sahiwal', 'province_id' => 2],
            ['name' => 'Sargodha', 'province_id' => 2],
            ['name' => 'Sheikhupura', 'province_id' => 2],
            ['name' => 'Sialkot', 'province_id' => 2],
            ['name' => 'Toba Tek Singh', 'province_id' => 2],
            ['name' => 'Vehari', 'province_id' => 2],
            ['name' => 'Awaran', 'province_id' => 3],
            ['name' => 'Barkhan', 'province_id' => 3],
            ['name' => 'Chagai', 'province_id' => 3],
            ['name' => 'Chaman', 'province_id' => 3],
            ['name' => 'Dera Bugti', 'province_id' => 3],
            ['name' => 'Duki', 'province_id' => 3],
            ['name' => 'Gwadar', 'province_id' => 3],
            ['name' => 'Harnai', 'province_id' => 3],
            ['name' => 'Jaffarabad', 'province_id' => 3],
            ['name' => 'Jhal Magsi', 'province_id' => 3],
            ['name' => 'Kachhi', 'province_id' => 3],
            ['name' => 'Kalat', 'province_id' => 3],
            ['name' => 'Kech', 'province_id' => 3],
            ['name' => 'Kharan', 'province_id' => 3],
            ['name' => 'Khuzdar', 'province_id' => 3],
            ['name' => 'Killa Abdullah', 'province_id' => 3],
            ['name' => 'Killa Saifullah', 'province_id' => 3],
            ['name' => 'Kohlu', 'province_id' => 3],
            ['name' => 'Lasbela', 'province_id' => 3],
            ['name' => 'Lehri', 'province_id' => 3],
            ['name' => 'Loralai', 'province_id' => 3],
            ['name' => 'Mastung', 'province_id' => 3],
            ['name' => 'Musa khail', 'province_id' => 3],
            ['name' => 'Nasirabad', 'province_id' => 3],
            ['name' => 'Nushki', 'province_id' => 3],
            ['name' => 'Panjgur', 'province_id' => 3],
            ['name' => 'Pishin', 'province_id' => 3],
            ['name' => 'Quetta', 'province_id' => 3],
            ['name' => 'Sherani', 'province_id' => 3],
            ['name' => 'Sibi', 'province_id' => 3],
            ['name' => 'Sohbatpur', 'province_id' => 3],
            ['name' => 'Surab', 'province_id' => 3],
            ['name' => 'Washuk', 'province_id' => 3],
            ['name' => 'Zhob', 'province_id' => 3],
            ['name' => 'Ziarat', 'province_id' => 3],
            ['name' => 'Abbottabad', 'province_id' => 4],
            ['name' => 'Bajaur', 'province_id' => 4],
            ['name' => 'Bannu', 'province_id' => 4],
            ['name' => 'Batagram', 'province_id' => 4],
            ['name' => 'Buner', 'province_id' => 4],
            ['name' => 'Charsadda', 'province_id' => 4],
            ['name' => 'Lower Chitral', 'province_id' => 4],
            ['name' => 'Upper Chitral', 'province_id' => 4],
            ['name' => 'Dera Ismail Khan', 'province_id' => 4],
            ['name' => 'Hangu', 'province_id' => 4],
            ['name' => 'Haripur', 'province_id' => 4],
            ['name' => 'Karak', 'province_id' => 4],
            ['name' => 'Khyber', 'province_id' => 4],
            ['name' => 'Kohat', 'province_id' => 4],
            ['name' => 'Kurram', 'province_id' => 4],
            ['name' => 'Lakki Marwat', 'province_id' => 4],
            ['name' => 'Lower Dir', 'province_id' => 4],
            ['name' => 'Lower Kohistan', 'province_id' => 4],
            ['name' => 'Malakand', 'province_id' => 4],
            ['name' => 'Mansehra', 'province_id' => 4],
            ['name' => 'Mardan', 'province_id' => 4],
            ['name' => 'Mohmand', 'province_id' => 4],
            ['name' => 'North Waziristan', 'province_id' => 4],
            ['name' => 'Nowshera', 'province_id' => 4],
            ['name' => 'Orakzai', 'province_id' => 4],
            ['name' => 'Peshawar', 'province_id' => 4],
            ['name' => 'Shangla', 'province_id' => 4],
            ['name' => 'South Waziristan', 'province_id' => 4],
            ['name' => 'Swabi', 'province_id' => 4],
            ['name' => 'Swat', 'province_id' => 4],
            ['name' => 'Tank', 'province_id' => 4],
            ['name' => 'Torghar', 'province_id' => 4],
            ['name' => 'Upper Dir', 'province_id' => 4],
            ['name' => 'Upper Kohistan', 'province_id' => 4],
            ['name' => 'Astore', 'province_id' => 5],
            ['name' => 'Deral', 'province_id' => 5],
            ['name' => 'Diamer', 'province_id' => 5],
            ['name' => 'Ghanche', 'province_id' => 5],
            ['name' => 'Gilgit', 'province_id' => 5],
            ['name' => 'Ghizer', 'province_id' => 5],
            ['name' => 'Hunza', 'province_id' => 5],
            ['name' => 'Kharmang', 'province_id' => 5],
            ['name' => 'Rondu', 'province_id' => 5],
            ['name' => 'Skardu', 'province_id' => 5],
            ['name' => 'Shigar', 'province_id' => 5],
            ['name' => 'Tangir', 'province_id' => 5],
            ['name' => 'Yaseen', 'province_id' => 5],
            ['name' => 'Nagar', 'province_id' => 5],
            ['name' => 'Bhimber', 'province_id' => 6],
            ['name' => 'Bagh', 'province_id' => 6],
            ['name' => 'Hattian', 'province_id' => 6],
            ['name' => 'Haveli', 'province_id' => 6],
            ['name' => 'Kotli', 'province_id' => 6],
            ['name' => 'Mirpur', 'province_id' => 6],
            ['name' => 'Muzaffarabad', 'province_id' => 6],
            ['name' => 'Neelum', 'province_id' => 6],
            ['name' => 'Poonch', 'province_id' => 6],
            ['name' => 'Sudhnoti', 'province_id' => 6],
        ];

        DB::table('districts')->insert($districts);


    }
}
